services:
  db:
    image: postgres:15.3
    container_name: workout_db
    environment:
      - POSTGRES_USER=workout
      - POSTGRES_PASSWORD=workout
      - POSTGRES_DB=workout
    ports:
      - "5432:5432"